name = "Jisaq"
uuid = "28b5d5bc-1f92-4a02-8fcd-b5fd77aed442"
authors = ["Satoru <sator8879@gmail.com>"]
version = "0.1.0"

[deps]
BenchmarkTools = "6e4b80f9-dd63-53aa-95a3-0cdb28fa8baf"
KrylovKit = "0b1a1467-8014-51b9-945f-bf0ae24f4b77"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
TensorKit = "07d1fe3e-3e46-537d-9eac-e9e13d0d4cec"

[weakdeps]
CUDA = "052768ef-5323-5732-b1bb-66c8b64840ba"

[extensions]
CuJisaq = "CUDA"

[compat]
BenchmarkTools = "1"
KrylovKit = "0.9"
LinearAlgebra = "1"
Random = "1"
SparseArrays = "1"
TensorKit = "0.14"
CUDA = "5"
julia = "1"